version: '2'
services:

  # Cerebro Elasticsearch client
  cerebro:
    build: .
    environment:
      - APP_SECRET="00oUafDtILqSFOhcpb8Zye4aU8Z7kGA9"
      - APP_URL=http://elasticsearch:9200
      - APP_NAME=teste
      - APP_USERNAME=teste
      - APP_PASSWORD=1234
    ports:
      - "9000:9000"
    links:
      - elasticsearch:elasticsearch
    networks:
      - app_net
  # Elasticsearch cluster
  elasticsearch:
    image: gerencio/elasticsearch:5.6.2-rev2
    environment:
      - DISCOVER_HTTP_IP=eth0
      - DISCOVER_TRANSPORT_IP=eth0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
